version: "3.2"
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_development
    ports:
      - 5432:5432
volumes:
  postgres_data:
